FINECAP/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
    path("", include("stands.urls", namespace="stands")),
    path("", include("main.urls", namespace="reservas")),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('reservas/list/', views.ReservasListView.as_view(), name='Listagem'),
    path('reservas/detail/<int:pk>/', views.ReservaDetailView.as_view(), name='reservas-detail'),
    path('reservas/update/<int:pk>/', views.ReservaUpdateView.as_view(), name='reservas-update'),
    path('reservas/delete/<int:pk>/', views.ReservaDeleteView.as_view(), name='reservas-delete'),
    path('reservas/create/', views.ReservaCreateView.as_view(), name='reservas-create'),
]

stands/urls.py
from django.urls import path

from . import views

app_name = "stands"
urlpatterns = [
    path('stands/list/', views.StandsListView.as_view(), name='stands-list'),
    path('stands/detail/<int:pk>/', views.StandDetailView.as_view(), name='stands-detail'),
    path('stands/update/<int:pk>/', views.StandUpdateView.as_view(), name='stands-update'),
    path('stands/delete/<int:pk>/', views.StandDeleteView.as_view(), name='stands-delete'),
    path('stands/create/', views.StandCreateView.as_view(), name='stands-create'),
]

stands/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.constants import (MAX_CHAR_FIELD_NAME_LENGTH,
                            MEDIUM_CHAR_FIELD_NAME_LENGTH,
                            SMALL_CHAR_FIELD_NAME_LENGTH)
from core.models import BaseModel


# Create your models here.
class Stand(BaseModel):

    localizacao = models.CharField(
        verbose_name=_("Localização"), max_length=SMALL_CHAR_FIELD_NAME_LENGTH
    )
    valor = models.DecimalField(
        verbose_name=_("Valor"),
        decimal_places=2,
        max_digits=6
    )

    class Meta:
        verbose_name = _("Stand")
        verbose_name_plural = _("Stands")

    def __str__(self):
        return f"{self.pk} | {self.localizacao} | {self.valor}"

stands/forms.py
from django import forms
from decimal import Decimal

from stands.models import Stand


class StandForm(forms.ModelForm):

    localizacao = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Localização do stand",
        })
    )
    valor = forms.CharField(
        widget=forms.TextInput(attrs={
            "class": "money form-control", 
            "placeholder": "Valor do stand",
})
)

    def clean_valor(self):
        valor = self.cleaned_data["valor"]
        return valor.replace(",", ".")
    
    def clean_localizacao(self):
        localizacao = self.cleaned_data["localizacao"]
        if localizacao == "Guilherme":
            raise forms.ValidationError(
                "O campo localização não pode ser Guilherme.",
            )
        return localizacao

    class Meta:
        model = Stand
        fields = (
            "localizacao",
            "valor",
        )

stands/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages import views
from django.urls import reverse_lazy
from django.views import generic

from .forms import StandForm
from .models import Stand


# Create your views here.
class StandsListView(LoginRequiredMixin, generic.ListView):
    model = Stand
    paginate_by = 5

    def get_queryset(self):
        return Stand.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_stands'] = Stand.objects.count()
        return context

class StandDetailView(LoginRequiredMixin, generic.DetailView):
    model = Stand

class StandCreateView(LoginRequiredMixin, views.SuccessMessageMixin, generic.CreateView):
    model = Stand
    form_class = StandForm
    success_url = reverse_lazy("stands:stands-list")
    success_message = "Stand cadastrado com sucesso!"

class StandUpdateView(LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = Stand
    form_class = StandForm
    success_url = reverse_lazy("stands:stands-list")
    success_message = "Stand atualizada com sucesso!"

class StandDeleteView(LoginRequiredMixin, views.SuccessMessageMixin, generic.DeleteView):
    model = Stand
    success_url = reverse_lazy("stands:stands-list")
    success_message = "Stand deletada com sucesso"

stands/templates/stands/stand_confirm_delete.html
<form method="post" action="{% url 'stands:stands-delete' object.id %}">
    {% csrf_token %}
    <div class="modal fade" id="modalExemplo-{{ object.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirmação de Exclusão</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Você tem certeza de que deseja remover o stand {{ object }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </div>
            </div>
        </div>
    </div>
  </form>
  

stands/templates/stands/stand_detail.html
<form method="post" action="{% url 'main:reservas-detail' object.id %}">
    {% csrf_token %}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="container my-5">
            <a class="btn btn-outline-primary btn-sm mb-3" href="{% url 'main:Listagem' %}">
                <i class="fas fa-arrow-left"></i> Voltar
            </a>
        
            <div class="card mx-auto" style="max-width: 400px;">
                <div class="card-body">
                    <h3 class="card-title text-primary">{{ object.localizacao }}</h3>
                    <p class="card-text"><strong>Valor:</strong> {{ object.valor }}</p>
                </div>
            </div>
        </div>
    </div>

</form>

stands/templates/stands/stand_form.html
{%  extends 'base.html' %}

{% block body %}
<br>

    <main>
    <div class="container px-4 px-lg-5 mt-5">
        <section class="sct-form">
            <div class="form">
                <h1 style="margin-bottom: 40px;">Reserve o seu stand já!</h1>
                   
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="cnpj" class="form-label">Localização</label>
                        {{ form.localizacao }}
                    </div>
                    <div class="mb-3">
                        <label for="nome_empresa" class="form-label">Valor</label>
                        {{ form.valor }}
                    </div>          
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>    

            </div>
     
        </section>
    </div> 
    
    </main>

    {% endblock %}
    

stands/templates/stands/stand_list.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-4">
  <h3 class="mb-4">Lista de Reservas</h3>
  <div class="d-flex align-items-center">
    <a href="{% url 'stands:stands-create' %}" class="btn btn-success mb-3" style="margin-top: 10px;">
        <i class="fas fa-plus"></i> Novo Cadastro
    </a>
    <div class="card ml-3" style ="margin-left: 15px;">
        <div class="card-body">
            <p class="card-text">Total de Stands: {{ num_stands }}</p>
        </div>
    </div>
</div>


  <table class="table table-striped mt-3">
      <thead class="thead-primary">
          <tr>
            <th>Detalhes</th>
            <th>Localização</th>
            <th>Valor</th>
            <th>Ações</th>
          </tr>
      </thead>
      <tbody>
          {% for object in object_list %}
              <tr>
                  <td>
                      <a data-toggle="modal" data-target=".bd-example-modal-lg" style="margin-left: 15px;">
                          &#128269;
                      </a>
                      {% include "stands/stand_detail.html" %}
                  </td>
                  <td>{{ object.localizacao }}</td>
                  <td>{{ object.valor }}</td>
                  <td>
                      <div class="d-flex align-items-center">
                          <a href="{% url 'stands:stands-update' object.id %}" class="btn btn-primary btn-sm mr-2">
                              <i class="fas fa-edit"></i>
                          </a>
                          <a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalExemplo-{{ object.id }}">
                            <i class="fas fa-trash"></i>
                        </a>
                        {% include "stands/stand_confirm_delete.html" %}
                      </div>
                  </td>
              </tr>
          {% empty %}
              <tr>
                  <td colspan="6">
                      <p>Não existem reservas cadastradas.</p>
                  </td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
</div>
<span class="br-divider my-3"></span>

{% if page_obj.has_other_pages %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        Previous
                    </a>
                </li>
            {% endif %}

            {% for page_number in page_obj.paginator.page_range %}
                {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                    {% if page_obj.number == page_number %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_number }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                        Last
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

{%  endblock %}