FINECAP/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
    path("", include("stands.urls", namespace="stands")),
    path("", include("main.urls", namespace="reservas")),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('reservas/list/', views.ReservasListView.as_view(), name='Listagem'),
    path('reservas/detail/<int:pk>/', views.ReservaDetailView.as_view(), name='reservas-detail'),
    path('reservas/update/<int:pk>/', views.ReservaUpdateView.as_view(), name='reservas-update'),
    path('reservas/delete/<int:pk>/', views.ReservaDeleteView.as_view(), name='reservas-delete'),
    path('reservas/create/', views.ReservaCreateView.as_view(), name='reservas-create'),
]

stands/urls.py
from django.urls import path

from . import views

app_name = "stands"
urlpatterns = [
    path('stands/list/', views.StandsListView.as_view(), name='stands-list'),
    path('stands/detail/<int:pk>/', views.StandDetailView.as_view(), name='stands-detail'),
    path('stands/update/<int:pk>/', views.StandUpdateView.as_view(), name='stands-update'),
    path('stands/delete/<int:pk>/', views.StandDeleteView.as_view(), name='stands-delete'),
    path('stands/create/', views.StandCreateView.as_view(), name='stands-create'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>FINECAP</title>

        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        {% block css %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        {% endblock %}

            <!-- Fonte Rawline-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdngovbr-ds.estaleiro.serpro.gov.br/design-system/fonts/rawline/css/rawline.css"/>
    <!-- Fonte Raleway-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900&amp;display=swap"/>
    <!-- Design System de Governo-->
    <link rel="stylesheet" href="{% static 'node_modules\@govbr-ds\core\dist\core.min.css' %}" />
    <!-- Fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <!-- Inclua o CSS do Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<!-- Inclua o jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    </head>

    <body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'core:home' %}">Finecap</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            Gerencia
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'main:Listagem' %}">Reservas</a></li>
            <li><a class="dropdown-item" href="{% url 'stands:stands-list' %}">Stands</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <section class="d-flex">
        <div class="header-login">
          {% if request.user.is_anonymous %}
          <div class="btn-group" role="group" aria-label="Entrar ou Cadastrar">
            <a href="#" class="btn btn-primary" type="button" data-trigger="login">
              <i class="fas fa-user" aria-hidden="true"></i> Entrar
            </a>
            <a href="{% url 'account_signup' %}" class="btn btn-primary" type="button">
              <i class="fas fa-user-plus" aria-hidden="true"></i> Cadastrar-se
            </a>
          </div>
          {% endif %}
          {% if request.user.is_authenticated %}
          <div class="header-avatar text-center">
            <div class="avatar dropdown mx-auto">
              <button class="btn btn-secondary btn-round dropdown-toggle" type="button" id="userMenu"
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user" aria-hidden="true"></i>
              </button>
              <div class="dropdown-menu user-menu" aria-labelledby="userMenu">
                <div class="row">
                  <div class="col-12 text-center">
                    <div class="user-info my-auto">
                      <h4 class="text-bold">{{ request.user }}</h4>
                      <small>{{ request.user.email }}</small><br />
                      <small><a style="text-decoration: none;" href="{% url 'account_change_password' %}">Alterar senha</a></small>
                    </div>
                  </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                  <div class="col-12 text-center">
                    <form method="post" action="{% url 'account_logout' %}">
                      {% csrf_token %}
                      {% if redirect_field_value %}
                      <input type="hidden" name="{{ redirect_field_name }}"
                             value="{{ redirect_field_value }}" />
                      {% endif %}
                      <button class="btn btn-danger btn-round btn-block" type="submit">
                        <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                      </button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endif %}                 
        </div>
      </section>
    </div>
  </div>
</nav>


  
    <main>    
      <div class="main-content pl-sm-3 mt-4" id="main-content">
        {% if messages %}
        {% include "layouts/messages.html" %}
      {% endif %}
      
      {% if form %}
        {% include "layouts/alerts.html" %}
      {% endif %}
        {% block body %}

        {% endblock %}

      </div>

    </main> 
      <!-- Scripts do Bootstrap (JQuery e Popper.js são necessários) -->
      {% block javascript %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

      <script>
        $(document).ready(function(){
          $('.money').mask('0000,00', {reverse: true})
          $('.cnpj').mask('00.000.000/0000-00', {reverse: true})
        })
      </script>

      <script>
        function togglePassword(button, passwordInput) {
            button.addEventListener("click", function() {
                if (passwordInput.type === "password") {
                    passwordInput.type = "text";
                } else {
                    passwordInput.type = "password";
                }
            });
        }
        
        document.addEventListener("DOMContentLoaded", function() {
            const toggleButtons = document.querySelectorAll(".toggle-button");
            const passwordInputs = document.querySelectorAll(".toggle-password");
        
            toggleButtons.forEach(function(button, index) {
                togglePassword(button, passwordInputs[index]);
            });
        });
        </script>
        
        

      {% endblock javascript %}
  </body>

  </html>