FINECAP/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("core.urls", namespace="core")),
    path("", include("stands.urls", namespace="stands")),
    path("", include("main.urls", namespace="reservas")),
]

core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path('reservas/list/', views.ReservasListView.as_view(), name='Listagem'),
    path('reservas/detail/<int:pk>/', views.ReservaDetailView.as_view(), name='reservas-detail'),
    path('reservas/update/<int:pk>/', views.ReservaUpdateView.as_view(), name='reservas-update'),
    path('reservas/delete/<int:pk>/', views.ReservaDeleteView.as_view(), name='reservas-delete'),
    path('reservas/create/', views.ReservaCreateView.as_view(), name='reservas-create'),
]

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.constants import (MAX_CHAR_FIELD_NAME_LENGTH,
                            MEDIUM_CHAR_FIELD_NAME_LENGTH,
                            SMALL_CHAR_FIELD_NAME_LENGTH)
from core.models import BaseModel
from stands.models import Stand
    
class Categoria(BaseModel):
    categoria_empresa = models.CharField(max_length=MEDIUM_CHAR_FIELD_NAME_LENGTH)

    def __str__(self):
        return f"{self.pk} | {self.categoria_empresa}"

class Reserva(BaseModel):

    cnpj_empresa = models.CharField(
        verbose_name=_("CNPJ Empresa"), max_length=SMALL_CHAR_FIELD_NAME_LENGTH, null=True
    )
    nome_empresa = models.CharField(
        verbose_name=_("Nome Empresa"), max_length=MAX_CHAR_FIELD_NAME_LENGTH
    )
    categoria_empresa = models.ForeignKey(Categoria, on_delete=models.CASCADE,)

    quitado = models.BooleanField(_("Quitado"), default=False)
    
    stand = models.ForeignKey(
        Stand,
        verbose_name=_("Stand"),
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = _("Reserva")
        verbose_name_plural = _("Reservas")

    def __str__(self):
        return f"{self.pk} | {self.cnpj_empresa} | {self.quitado}"

main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Stand, Reserva
from stands.models import Stand

class ReservaForm(ModelForm):

    class Meta:
        model = Reserva
        widgets = {
            'cnpj_empresa' : forms.TextInput(attrs={'class': 'cnpj form-control',"placeholder": "CNPJ da empresa", }),
            'nome_empresa' : forms.TextInput(attrs={'class': 'form-control',"placeholder": "Nome da empresa", }),
            'categoria_empresa' : forms.Select(attrs={'class': 'form-control', }),
            'quitado': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'stand': forms.Select(attrs={'class': 'form-control', }),

        }

        fields = (
            'cnpj_empresa',
            'nome_empresa',
            'categoria_empresa',
            'quitado',
            'stand',
        )

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.messages import views
from .forms import ReservaForm
from .models import Reserva
from users.permissions import GerentePermission

class ReservasListView(GerentePermission, LoginRequiredMixin, generic.ListView):
    model = Reserva
    template_name = "main/Listagem.html"
    paginate_by = 5

    def get_queryset(self):
        return Reserva.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_reservas'] = Reserva.objects.count()
        return context

class ReservaCreateView(GerentePermission, LoginRequiredMixin, views.SuccessMessageMixin,generic.CreateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy("main:Listagem")
    template_name = "main/reservas-create.html"
    success_message = "Reserva criada com sucesso"



class ReservaDeleteView(GerentePermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.DeleteView):
    model = Reserva
    success_url = reverse_lazy("main:Listagem")
    success_message = "Reserva deletada com sucesso"


class ReservaDetailView(GerentePermission, LoginRequiredMixin, generic.DetailView):
    model = Reserva


class ReservaUpdateView(GerentePermission, LoginRequiredMixin, views.SuccessMessageMixin, generic.UpdateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy("main:Listagem")
    template_name = "main/reservas-create.html"
    success_message = "Reserva atualizada com sucesso"

main/templates/main/Listagem.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-4">
  <h3 class="mb-4">Lista de Reservas</h3>
  <div class="d-flex align-items-center">
    <a href="{% url 'main:reservas-create' %}" class="btn btn-success mb-3" style="margin-top: 10px;">
        <i class="fas fa-plus"></i> Novo Cadastro
    </a>
    <div class="card ml-3" style ="margin-left: 15px;">
        <div class="card-body">
            <p class="card-text">Total de Reservas: {{ num_reservas }}</p>
        </div>
    </div>
</div>


  <table class="table table-striped mt-3">
      <thead class="thead-primary">
          <tr>
              <th>Detalhes</th>
              <th>CNPJ</th>
              <th>Nome da Empresa</th>
              <th>Categoria</th>
              <th>Quitado</th>
              <th>Ações</th>
          </tr>
      </thead>
      <tbody>
          {% for object in object_list %}
              <tr>
                  <td>
                      <a data-toggle="modal" data-target=".bd-example-modal-lg" style="margin-left: 15px;">
                          &#128269;
                      </a>
                      {% include "main/reserva_detail.html" %}
                  </td>
                  <td>{{ object.cnpj_empresa }}</td>
                  <td>{{ object.nome_empresa }}</td>
                  <td>{{ object.categoria_empresa }}</td>
                  <td>{% if object.quitado %} Sim {% else %} Não {% endif %}</td>
                  <td>
                      <div class="d-flex align-items-center">
                          <a href="{% url 'main:reservas-update' object.id %}" class="btn btn-primary btn-sm mr-2">
                              <i class="fas fa-edit"></i>
                          </a>
                          <a class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalExemplo-{{ object.id }}">
                              <i class="fas fa-trash"></i>
                          </a>
                          {% include "main/reserva_confirm_delete.html" %}
                      </div>
                  </td>
              </tr>
          {% empty %}
              <tr>
                  <td colspan="6">
                      <p>Não existem reservas cadastradas.</p>
                  </td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
</div>
<span class="br-divider my-3"></span>

{% if page_obj.has_other_pages %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        Previous
                    </a>
                </li>
            {% endif %}

            {% for page_number in page_obj.paginator.page_range %}
                {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                    {% if page_obj.number == page_number %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_number }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                        Last
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

{%  endblock %}

main/templates/main/detalhe_reserva.html
{% extends 'base.html' %}

{% block body %}
<main>
    <table class="bg-gray-2">
    
        <h1>Visualizar Reserva</h1>
        
        <div>
            <p class="text-weight-bold">Dados da Reserva:</p>
      
            <section class="container-fluid p-2x">
              <div class="content" id="idsn30">
                <div class="row align-items-center mb-2">
                  <div class="col-md-1 col-sm-12 text-weight-bold">CNPJ:</div>
                  <div id="cnpj-empresa" class="col-md-11 col-sm-12">{{ object.cnpj_empresa }}</div>
                </div>
                <div class="row align-items-center mb-2">
                  <div class="col-md-1 col-sm-12 text-weight-bold">Nome:</div>
                  <div id="nome-empresa" class="col-md-11 col-sm-12">{{ object.nome_empresa }}</div>
                </div>
                <div class="row align-items-center mb-2">
                  <div class="col-md-1 col-sm-12 text-weight-bold">Categoria:</div>
                  <div id="categoria-empresa" class="col-md-11 col-sm-12">{{ object.get_categoria_empresa_display }}</div>
                </div>
                <div class="row align-items-center mb-2">
                  <div class="col-md-1 col-sm-12 text-weight-bold">Status:</div>
                  {% if object.quitado %}
                    <div id="opcao" class="col-md-11 col-sm-12">Pagamento Efetuado</div>
                  {% else %}
                    <div id="opcao" class="col-md-11 col-sm-12">Pagamento Pendente</div>
                  {% endif %}
                </div>
                <div class="row align-items-center mb-2">
                    <div class="col-md-1 col-sm-12 text-weight-bold">Stand:</div>
                    <div id="opcao" class="col-md-11 col-sm-12">{{ object.stand }}</div>
                  </div>
            </section>
            
            <section class="container-fluid pt-2x">
              <div class="row justify-content-between">
                  <div class="col-lg-1 col-md-1 col-12">
                    <a class="br-button block" href="{% url 'stands:reservas-list' %}" type="button">
                      <i class="fas fa-chevron-left mr-1" aria-hidden="true"></i>
                      Voltar
                    </a>
                  </div>
              
                  <div class="col-lg-5 col-md-5 col-12 mt-3 mt-md-0">
                    <a
                      style="text-decoration: none"
                      href="{% url 'stands:reservas-update' object.pk %}"
                      class="br-button primary block mt-3 mt-sm-0 p-0"
                      type="button"
                    >
                      <i class="fas fa-edit mr-1" aria-hidden="true"></i>
                      Editar
                    </a>
                  </div>
              </div>
            </section>
        </div>
    </table>
    
</main>
    {%endblock%}

main/templates/main/reserva.html
{%  extends 'base.html' %}

{% block body %}
<br>

    <main>
    <div class="container px-4 px-lg-5 mt-5">
        <section class="sct-form">
            <div class="form">
                <h1 style="margin-bottom: 40px;">Reserve o seu stand já!</h1>
                   
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="cnpj" class="form-label">CNPJ</label>
                        {{ form.cnpj }}
                    </div>
                    <div class="mb-3">
                        <label for="nome_empresa" class="form-label">Nome da empresa</label>
                        {{ form.nome_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="empresa_categoria'" class="form-label">Categoria da empresa</label>
                        {{ form.categoria_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="Stand" class="form-label">Selecione o Stand</label>
                        {{ form.stand }}
                    </div>
                    <div class="col-md-1 col-lg-1 col-12">
                        <div class="br-input">
                            {{ form.quitado.label_tag }}
                            {{ form.quitado }}
                        </div>
                    </div>
                    
                    
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>    

            </div>
     
        </section>
    </div> 
    
    </main>

    {% endblock %}
    

main/templates/main/reserva_confirm_delete.html
<form method="post" action="{% url 'main:reservas-delete' object.id %}">
  {% csrf_token %}
  <div class="modal fade" id="modalExemplo-{{ object.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Confirmação de Exclusão</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                  Você tem certeza de que deseja remover a reserva {{ object }}?
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                  <button type="submit" class="btn btn-danger">Deletar</button>
              </div>
          </div>
      </div>
  </div>
</form>

main/templates/main/reserva_detail.html
<form method="post" action="{% url 'main:reservas-detail' object.id %}">
    {% csrf_token %}
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="container my-5">
            <a class="btn btn-outline-primary btn-sm mb-3" href="{% url 'main:Listagem' %}">
                <i class="fas fa-arrow-left"></i> Voltar
            </a>
        
            <div class="card mx-auto" style="max-width: 400px;">
                <div class="card-body">
                    <h3 class="card-title text-primary">{{ object.nome_empresa }}</h3>
                    <p class="card-text"><strong>CNPJ:</strong> {{ object.cnpj }}</p>
                    <p class="card-text"><strong>Categoria:</strong> {{ object.categoria_empresa }}</p>
                    <p class="card-text"><strong>Quitado:</strong> {% if object.quitado %} Sim {% else %} Não {% endif %}</p>
                    <p class="card-text"><strong>Stand:</strong> {{ object.stand }}</p>
                    <p class="card-text"><strong>Valor do Stand:</strong> R$ {{ object.stand.valor|floatformat:2 }}</p>
                </div>
            </div>
        </div>
    </div>

</form>

main/templates/main/reservas-create.html
{%  extends 'base.html' %}

{% block body %}
<br>

    <main>
    <div class="container px-4 px-lg-5 mt-5">
        <section class="sct-form">
            <div class="form">
                <h1 style="margin-bottom: 40px;">Reserve o seu stand já!</h1>
                   
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="cnpj" class="form-label">CNPJ</label>
                        {{ form.cnpj_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="nome_empresa" class="form-label">Nome da empresa</label>
                        {{ form.nome_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="empresa_categoria'" class="form-label">Categoria da empresa</label>
                        {{ form.categoria_empresa }}
                    </div>
                    <div class="mb-3">
                        <label for="Stand" class="form-label">Selecione o Stand</label>
                        {{ form.stand }}
                    </div>
                    <div class="col-md-1 col-lg-1 col-12">
                        <div class="form-check">
                            {{ form.quitado }}
                            <label class="form-check-label" for="{{ form.quitado.id_for_label }}">Quitado</label>
                        </div>                                              
                    </div>
            
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>    

            </div>
     
        </section>
    </div> 
    
    </main>

    {% endblock %}
    